name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint (Optional)
      run: |
        pip install flake8
        flake8 app --max-line-length=120

    - name: Test run API
      run: |
        uvicorn app.main:app --host 127.0.0.1 --port 8000 &
        sleep 5
        curl -X 'POST' \
          'http://127.0.0.1:8000/predict' \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -d '{"features":[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1.0]}'